/* ═══════════════════════════════════════
   HUMAN ENCYCLOPEDIA (人類圖鑑) DATA
═══════════════════════════════════════ */

export const HUMAN_CATEGORIES = [
  { id: 'citizens', name: '一般市民', icon: '🏙️' },
  { id: 'workers',  name: '職人服務業', icon: '👷' },
  { id: 'subculture', name: '亞文化奇人', icon: '🎨' },
  { id: 'rare',     name: '稀有與傳說', icon: '✨' },
];

export const HUMAN_ITEMS = [
  // ── Category 1: 一般市民 ──
  {
    id: 'h-01',
    categoryId: 'citizens',
    name: '西裝上班族',
    icon: '👨‍💼',
    count: 999,
    unlocked: true,
    description: '每天擠電車的通勤族，富含咖啡因與維他命B群。',
  },
  {
    id: 'h-02',
    categoryId: 'citizens',
    name: '提包小資女',
    icon: '👩‍💼',
    count: 782,
    unlocked: true,
    description: '手拿拿鐵咖啡，對美食與休假有著極高的執著。',
  },
  {
    id: 'h-03',
    categoryId: 'citizens',
    name: '觀光遊客',
    icon: '🧳',
    count: 432,
    unlocked: true,
    description: '相機不離身，總是神采奕奕地在地圖前徘徊。',
  },
  {
    id: 'h-04',
    categoryId: 'citizens',
    name: '運動跑者',
    icon: '🏃',
    count: 136,
    unlocked: true,
    description: '腳程飛快且活力充沛，提供高密度的肌肉能量。',
  },
  {
    id: 'h-05',
    categoryId: 'citizens',
    name: '散步老伯',
    icon: '👴',
    count: 516,
    unlocked: true,
    description: '公園棋局的常勝軍，性格悠哉不慌不忙。',
  },
  {
    id: 'h-06',
    categoryId: 'citizens',
    name: '媽媽帶小孩',
    icon: '👩‍👧',
    count: 341,
    unlocked: true,
    description: '同時維持推車平衡與安撫嬰兒的超強多工市民。',
  },
  {
    id: 'h-07',
    categoryId: 'citizens',
    name: '吸珍奶 JK',
    icon: '🧋',
    count: 231,
    unlocked: true,
    description: '珍珠奶茶的熱量供給者，身上隨時帶著最新潮流資訊。',
  },
  {
    id: 'h-08',
    categoryId: 'citizens',
    name: '逛街學生',
    icon: '🎒',
    count: 123,
    unlocked: true,
    description: '課後聚集在商圈散步，充滿青春氣息。',
  },

  // ── Category 2: 職人與服務業 ──
  {
    id: 'h-09',
    categoryId: 'workers',
    name: '美食外送員',
    icon: '🛵',
    count: 852,
    unlocked: true,
    description: '穿梭大街小巷的都市血脈，隨機攜帶高卡路里餐點。',
  },
  {
    id: 'h-10',
    categoryId: 'workers',
    name: '巡邏警察',
    icon: '👮',
    count: 320,
    unlocked: true,
    description: '維護都市秩序的守衛者，富含正義感的優質養份。',
  },
  {
    id: 'h-11',
    categoryId: 'workers',
    name: '熱血消防員',
    icon: '👨‍🚒',
    count: 194,
    unlocked: true,
    description: '不怕火燒的鋼鐵男兒，口感紮實且耐力極高。',
  },
  {
    id: 'h-12',
    categoryId: 'workers',
    name: '工地阿舅',
    icon: '👷‍♂️',
    count: 468,
    unlocked: true,
    description: '保力達與保溫瓶的愛好者，肌肉結實的建造者。',
  },
  {
    id: 'h-13',
    categoryId: 'workers',
    name: '輪班工程師',
    icon: '👨‍💻',
    count: 610,
    unlocked: true,
    description: '常年熬夜的程式碼產出機器，含有大量提神飲料成分。',
  },
  {
    id: 'h-14',
    categoryId: 'workers',
    name: '主廚阿達',
    icon: '🧑‍🍳',
    count: 275,
    unlocked: true,
    description: '掌控廚房火候的美食大師，本身飄散著誘人香氣。',
  },

  // ── Category 3: 亞文化與奇人 ──
  {
    id: 'h-15',
    categoryId: 'subculture',
    name: '街頭吉他手',
    icon: '🎸',
    count: 188,
    unlocked: true,
    description: '站在地下道深情開唱，熱情充滿音樂靈魂。',
  },
  {
    id: 'h-16',
    categoryId: 'subculture',
    name: '貓耳 Cosplayer',
    icon: '🐱',
    count: 305,
    unlocked: true,
    description: '展覽會場的焦點，裝扮精緻度令人驚嘆。',
  },
  {
    id: 'h-17',
    categoryId: 'subculture',
    name: '極限滑板手',
    icon: '🛹',
    count: 142,
    unlocked: true,
    description: '將廣場階梯當成表演舞台，身手無比敏捷。',
  },
  {
    id: 'h-18',
    categoryId: 'subculture',
    name: '嘻哈饒舌歌手',
    icon: '🎤',
    count: 96,
    unlocked: true,
    description: '口吐蓮花的韻腳大師，靈魂自帶重低音節奏。',
  },
  {
    id: 'h-19',
    categoryId: 'subculture',
    name: '宅宅同人客',
    icon: '🤓',
    count: 512,
    unlocked: true,
    description: '戰利品滿滿的動漫愛好者，擁有無與倫比的熱情。',
  },
  {
    id: 'h-20',
    categoryId: 'subculture',
    name: '中二病勇者',
    icon: '🗡️',
    count: 77,
    unlocked: true,
    description: '右臂封印著漆黑之龍，深信自己才是都市拯救者。',
  },

  // ── Category 4: 稀有與傳說 ──
  {
    id: 'h-21',
    categoryId: 'rare',
    name: '璀璨金光富豪',
    icon: '💎',
    count: 15,
    unlocked: true,
    description: '身穿奢華金袍的頂級富豪，提供極高濃度的金光養份！',
  },
  {
    id: 'h-22',
    categoryId: 'rare',
    name: '時間旅行者',
    icon: '⏳',
    count: 3,
    unlocked: true,
    description: '來自未來的神秘訪客，身上流淌著時空裂縫的微光。',
  },
  {
    id: 'h-23',
    categoryId: 'rare',
    name: '外星難民',
    icon: '👽',
    count: 0,
    unlocked: false,
    unlockText: '在都市傳說事件中遭遇並吸收',
    description: '隱藏在人群中的宇宙訪客，尚未被吸收過。',
  },
  {
    id: 'h-24',
    categoryId: 'rare',
    name: '謎之黑衣人',
    icon: '🕶️',
    count: 0,
    unlocked: false,
    unlockText: '解開所有隱藏城市奇遇解鎖',
    description: '身份不明的秘密機關特務，深藏不露。',
  },
];
